# Generated by Django 5.1.1 on 2024-11-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetailDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('quantite', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('prix_unit', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('prix_tot', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('file_facture', models.FileField(blank=True, null=True, upload_to='media/facture')),
                ('description', models.TextField()),
                ('date_depense', models.DateField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.depense')),
                ('unite_mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.unitemesure')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
