# Generated by Django 5.1.1 on 2024-11-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_unitemesure_detaildepense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detaildepense',
            name='date_depense',
        ),
        migrations.RemoveField(
            model_name='detaildepense',
            name='file_facture',
        ),
        migrations.AlterField(
            model_name='detaildepense',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
