# Generated by Django 5.1.1 on 2024-11-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_detaildepense_date_depense_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitemesure',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelTable(
            name='unitemesure',
            table='unite_depense',
        ),
    ]
